var type = require('sequelize');
var sequelize = require('./sequelizeConnection');

var movContable = sequelize.define('movContable', {
    idMov: {
        type: type.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    pagina: type.INTEGER,
    pEmpId: type.INTEGER,
    Empresa: type.STRING,
    DivCodigo: type.INTEGER,
    DivGlosa: type.STRING,
    DigFecha: type.STRING,
    PerId: type.INTEGER,
    PerGlosa: type.STRING,
    SisCodOri: type.INTEGER,
    SisGlosa: type.STRING,
    OpeCod: type.INTEGER,
    OpeGlosa: type.STRING,
    NroInterno: type.BIGINT,
    Estado: type.INTEGER,
    ConEstGlosa: type.STRING,
    CtaCodigo: type.INTEGER,
    CtaNombre: type.STRING,
    MonedaId: type.INTEGER,
    MonGlosa: type.STRING,
    MovCceMontoImpuDebe: type.FLOAT,
    MovCceMontoImpuHaber: type.FLOAT,
    MovCceMontoLocalDebe: type.FLOAT,
    MovCceMontoLocalHaber: type.FLOAT,
    MovCceMontoConvDebe: type.FLOAT,
    MovCceMontoConvHaber: type.FLOAT,
    CreCodigo: type.INTEGER,
    CreNombre: type.STRING,
    CdiCodigo: type.INTEGER,
    CdiGlosa: type.STRING,
    EntRut: type.STRING,
    EntRazonSocial: type.STRING,
    TdoId: type.INTEGER,
    TdoGlosa: type.STRING,
    LlgDocNumDoc: type.STRING,
    TcoId: type.INTEGER,
    TcoGlosa: type.STRING,
    llgdocdigusuario: type.STRING,
    llgdocaprusuario: type.STRING,
    llgdocactusuario: type.STRING,
    TctId: type.INTEGER,
    TctGlosa: type.STRING,
    GlosaMovimiento: type.STRING,
    Nivel1: type.STRING,
    Nivel2: type.STRING,
    Nivel3: type.STRING,
    Nivel4: type.STRING,
    Nivel5: type.STRING,
    Nivel6: type.STRING,
    Nivel7: type.STRING,
    cabopelinea: type.BIGINT,
    pcabopeid: type.BIGINT,
    codigofinanciero: type.INTEGER,
    glosafinanciero: type.STRING,
    ctacte: type.STRING,
    banco: type.STRING,
    fechaComprobante: type.STRING,
    EjercicioContable: type.INTEGER,
    MovCCeId: type.BIGINT,
    ComNumero: type.BIGINT});
sequelize.sync();

module.exports = movContable;